### ISSUE TITLE
cmd showed an error when pasting IridiumSkyblockAddon-1.1.0.jar into the addons folder

### ISSUE THREAD

**Issue by tncc2k** [InsightsPlugin/IridiumSkyblockAddon#1]
IridiumSkyblock 2.6.7
Insights 5.8.0

cmd error code:

[07:53:21] [Server thread/ERROR]: Could not pass event EntityRemoveFromWorldEvent to Insights v5.8.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[skyblock1102.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[skyblock1102.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) ~[skyblock1102.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) ~[skyblock1102.jar:git-Spigot-de459a2-51263e9]
	at net.frankheijden.insights.listeners.EntityListener$EntityRemovalChecker.lambda$run$0(EntityListener.java:168) ~[?:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) [skyblock1102.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [skyblock1102.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [skyblock1102.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [skyblock1102.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [skyblock1102.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [skyblock1102.jar:git-Spigot-de459a2-51263e9]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.NoSuchMethodError: com.iridium.iridiumskyblock.IridiumSkyblock.getIslandManager()Lcom/iridium/iridiumskyblock/IslandManager;
	at net.frankheijden.insights.addons.iridiumskyblock.IridiumSkyblockAddon.getArea(IridiumSkyblockAddon.java:33) ~[?:?]
	at net.frankheijden.insights.managers.CacheManager.getSelections(CacheManager.java:71) ~[?:?]
	at net.frankheijden.insights.managers.CacheManager.newCacheLocation(CacheManager.java:115) ~[?:?]
	at net.frankheijden.insights.listeners.EntityListener.handleEntityChange(EntityListener.java:131) ~[?:?]
	at net.frankheijden.insights.listeners.EntityListener.onEntityRemoveFromWorld(EntityListener.java:115) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[skyblock1102.jar:git-Spigot-de459a2-51263e9]
	... 11 more

**Comment by FrankHeijden** [comment]
Thanks for reporting! Should be fixed with version v1.1.1.
